### PR TITLE
WR-1422 update Earnings source

### PR DESCRIPTION
**Pull request by rjkuyvenhoven**
has accompanying PR in workbc-main

### CODE REVIEW

**Review by infojunkie — COMMENTED** [review]
Did you check that the source label "YYYY Job Bank Wage data" is not showing anywhere else on the site?

**Comment by rjkuyvenhoven** [comment]
> Did you check that the source label "YYYY Job Bank Wage data" is not showing anywhere else on the site?

The only places this source label is used are the two instances indicated they wanted changed in the ticket.

**Review by infojunkie — APPROVED** [review]
Lgtm, thanks for cheecking.

**Comment by infojunkie** [comment]
You can merge this SSoT PR right away.

**Pull request merged**
